name: build-wasm-wheel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3' 

      - name: Build wheel
        run: python -m pip wheel . -w wheel_build

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: wheel_build/demoland*
