# SEE: https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=linux%2Cpython&pivots=method-manual
# This action is modified from https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-python-functionapp-on-azure.yml

name: Deploy demolandapi Azure Functions app

on:
  workflow_dispatch:   # Allows manual triggering via GitHub website
  push:
    branches:
      - main           # Any time main branch is pushed to

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'demolandapi' # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  azure-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    # I added this step. --fail-with-body makes this fail if any HTTP status
    # code >= 400 is returned
    - name: Test that deployment is working
      run: |
        curl -v --fail-with-body https://demolandapi.azurewebsites.net/api/scenario -d "{\"scenario_json\": {}, \"model_identifier\": \"tyne_and_wear\"}"
